# Generated by Django 4.0.5 on 2022-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_nationality_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
