# Generated by Django 4.0.5 on 2022-07-21 06:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_slider_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
    ]
