# Generated by Django 4.0.5 on 2022-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mimnimum',
            field=models.IntegerField(default=0),
        ),
    ]
