# Generated by Django 4.0.5 on 2022-07-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_mimnimum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mimnimum',
            new_name='minimum',
        ),
    ]
