# Generated by Django 4.0.5 on 2022-08-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_partner_product_color1_product_color2_product_color3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
